-- 코드를 입력하세요
SELECT MCDP_CD AS "진료과코드", COUNT(APNT_NO) AS "5월예약건수" FROM APPOINTMENT
WHERE APNT_YMD BETWEEN TO_DATE('20220501', 'YYYY-MM-DD')
AND TO_DATE('20220531', 'YYYY-MM-DD')
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO), MCDP_CD;

